CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '',image_key TEXT NOT NULL DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'published');
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,category_id INTEGER,summary TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',featured INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'draft',seo_title TEXT NOT NULL DEFAULT '',seo_description TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS product_images(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,object_key TEXT NOT NULL,alt_text TEXT NOT NULL DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,is_primary INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS product_specs(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,name TEXT NOT NULL,value TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,title TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,summary TEXT NOT NULL DEFAULT '',content TEXT NOT NULL DEFAULT '',cover_key TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',seo_title TEXT NOT NULL DEFAULT '',seo_description TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS videos(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '',video_key TEXT NOT NULL DEFAULT '',poster_key TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pages(page_key TEXT PRIMARY KEY,title TEXT NOT NULL DEFAULT '',subtitle TEXT NOT NULL DEFAULT '',content TEXT NOT NULL DEFAULT '',image_key TEXT NOT NULL DEFAULT '',seo_title TEXT NOT NULL DEFAULT '',seo_description TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS redirects(old_path TEXT PRIMARY KEY,new_path TEXT NOT NULL,status_code INTEGER NOT NULL DEFAULT 301);
CREATE TABLE IF NOT EXISTS inquiries(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL,company TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',message TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'new',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO settings(key,value) VALUES
('company_name','Shunmu Technology (Suzhou) Co.,LTD'),('phone','86-15150445122'),('whatsapp','8615150445122'),('email','SM@smusu.com'),('address','No. 408, Mudong Road, Mudu Town, Wuzhong District, Suzhou City, Jiangsu Province');
INSERT OR IGNORE INTO categories(name,slug,sort_order) VALUES
('Diamond Cutting Tools','diamond-cutting-tools',1),('Diamond Polishing Tools','diamond-polishing-tools',2),('Diamond Profiling Tools','diamond-profiling-tools',3),('Hand tools','hand-tools',4),('Diamond Drilling Tools','diamond-drilling-tools',5),('Diamond grinding tool','diamond-grinding-tool',6);
INSERT OR IGNORE INTO pages(page_key,title,subtitle,content) VALUES
('home','Engineered for the Cut. Built for the Finish.','Professional diamond tools for stone, concrete and advanced surfaces.','SMUSU delivers cutting, grinding, polishing, profiling and drilling solutions for professional applications.'),
('about','About Shunmu Technology','Diamond tool expertise from Suzhou to global markets.','We focus on professional diamond tools and long-term cooperation with customers worldwide.'),
('contact','Talk to Our Tool Specialists','Tell us your material, machine and application.','Our team will help you select a suitable solution.');
