const H={"content-type":"text/html; charset=utf-8"};
const esc=(v="")=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const J=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const slug=(v="")=>String(v).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
async function rows(db,sql,...a){return (await db.prepare(sql).bind(...a).all()).results||[]}
async function one(db,sql,...a){return await db.prepare(sql).bind(...a).first()}
async function settings(env){return Object.fromEntries((await rows(env.DB,"SELECT key,value FROM settings")).map(x=>[x.key,x.value]))}
async function siteData(env){return {s:await settings(env),cats:await rows(env.DB,"SELECT * FROM categories WHERE status='published' ORDER BY sort_order,id")}}
function logo(s){return s.logo_key?`<img class="logoImg" src="/media/${esc(s.logo_key)}" alt="${esc(s.site_name||'SMUSU')}">`:`<span class="logoText">${esc(s.site_name||'SMUSU')}</span>`}
function nav(cats){return `<nav class="navlinks"><a href="/">Home</a><a href="/about/">About</a><div class="drop"><a href="/products/">Products ▾</a><div class="dropmenu"><a href="/products/">All Products</a>${cats.map(c=>`<a href="/products/?category=${esc(c.slug)}">${esc(c.name)}</a>`).join('')}</div></div><div class="drop"><a href="/news/">News ▾</a><div class="dropmenu"><a href="/news/">All News</a><a href="/news/?type=company_news">Company News</a><a href="/news/?type=industry_news">Industry News</a></div></div><a href="/cases/">Cases</a><a href="/videos/">Videos</a><div class="drop"><a href="/contact/">Contact ▾</a><div class="dropmenu"><a href="/contact/">Contact Us</a><a href="/feedback/">Feedback</a></div></div></nav>`}
function shell(meta,body,d){const fav=d.s.favicon_key?`<link rel="icon" href="/media/${esc(d.s.favicon_key)}">`:'';return new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(meta.title||d.s.site_name||'SMUSU')}</title><meta name="description" content="${esc(meta.desc||'Professional diamond tools')}"><link rel="canonical" href="${esc(meta.canonical||'')}">${fav}<link rel="stylesheet" href="/site.css"></head><body><div class="top"><div class="wrap"><span>Welcome to ${esc(d.s.company_name||'Shunmu Technology')}</span><span>${esc(d.s.phone||'')}</span></div></div><header><div class="wrap navbar"><a class="brand" href="/">${logo(d.s)}</a>${nav(d.cats)}<button class="mobileBtn" onclick="document.body.classList.toggle('menuOpen')">☰</button></div></header>${body}<footer><div class="wrap footerGrid"><div><a class="brand" href="/">${logo(d.s)}</a><p>${esc(d.s.company_name||'')}</p></div><div><b>Products</b><p>${d.cats.map(c=>`<a href="/products/?category=${esc(c.slug)}">${esc(c.name)}</a>`).join('<br>')}</p></div><div><b>Contact</b><p>${esc(d.s.email||'')}<br>${esc(d.s.phone||'')}<br>${esc(d.s.address||'')}</p></div></div></footer></body></html>`,{headers:H})}
const mediaCard=(k,a)=>`<div class="media">${k?`<img src="/media/${esc(k)}" alt="${esc(a)}" loading="lazy">`:`<span>${esc(a)}</span>`}</div>`;
async function home(env){const d=await siteData(env),p=await one(env.DB,"SELECT * FROM pages WHERE page_key='home'"),about=await one(env.DB,"SELECT * FROM pages WHERE page_key='about'"),products=await rows(env.DB,"SELECT p.*,c.name category,(SELECT object_key FROM product_images i WHERE i.product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) image FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.status='published' ORDER BY featured DESC,id DESC LIMIT 6"),news=await rows(env.DB,"SELECT * FROM posts WHERE type IN ('news','company_news','industry_news') AND status='published' ORDER BY id DESC LIMIT 3"),cases=await rows(env.DB,"SELECT * FROM posts WHERE type='case' AND status='published' ORDER BY id DESC LIMIT 3");const body=`<section class="hero"><div class="wrap heroGrid"><div><div class="kicker">${esc(d.s.site_name||'SMUSU')} · SUZHOU</div><h1>${esc(p?.title||'Engineered for the Cut. Built for the Finish.')}</h1><p>${esc(p?.subtitle||'')}</p><a class="btn" href="/products/">Explore Products</a><a class="btn light" href="/feedback/">Request a Quote</a></div><div class="heroVisual"><div class="blade"></div></div></div></section><section><div class="wrap"><div class="sectionHead"><h2>Product Families</h2></div><div class="grid">${d.cats.map(c=>`<a class="card" href="/products/?category=${esc(c.slug)}">${mediaCard(c.image_key,c.name)}<div class="cardBody"><h3>${esc(c.name)}</h3><p>${esc(c.description||'')}</p></div></a>`).join('')}</div></div></section><section class="soft"><div class="wrap"><div class="sectionHead"><h2>Featured Products</h2></div><div class="grid">${products.map(x=>`<a class="card" href="/products/${esc(x.slug)}/">${mediaCard(x.image,x.name)}<div class="cardBody"><small>${esc(x.category||'')}</small><h3>${esc(x.name)}</h3><p>${esc(x.summary)}</p></div></a>`).join('')||'<div class="empty">No products yet.</div>'}</div></div></section><section><div class="wrap split"><div class="factory">${esc(d.s.site_name||'SMUSU')}</div><div><h2>${esc(about?.title||'About Us')}</h2><p>${esc(about?.content||'')}</p></div></div></section><section class="soft"><div class="wrap"><div class="sectionHead"><h2>Cases</h2></div><div class="grid">${cases.map(x=>`<a class="card" href="/${x.type==='case'?'cases':'news'}/${esc(x.slug)}/">${mediaCard(x.cover_key,x.title)}<div class="cardBody"><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p></div></a>`).join('')||'<div class="empty">No cases yet.</div>'}</div></div></section><section><div class="wrap"><div class="sectionHead"><h2>News</h2></div><div class="grid">${news.map(x=>`<a class="card" href="/${x.type==='case'?'cases':'news'}/${esc(x.slug)}/">${mediaCard(x.cover_key,x.title)}<div class="cardBody"><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p></div></a>`).join('')||'<div class="empty">No news yet.</div>'}</div></div></section>`;return shell({title:`${d.s.site_name||'SMUSU'} | Professional Diamond Tools`,canonical:env.SITE_URL+'/'},body,d)}
async function productList(env,u){const d=await siteData(env),cat=u.searchParams.get('category'),sql=`SELECT p.*,c.name category,(SELECT object_key FROM product_images i WHERE i.product_id=p.id ORDER BY is_primary DESC,sort_order,id LIMIT 1) image FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.status='published' ${cat?'AND c.slug=?':''} ORDER BY p.id DESC`,items=cat?await rows(env.DB,sql,cat):await rows(env.DB,sql);return shell({title:'Products | '+(d.s.site_name||'SMUSU'),canonical:env.SITE_URL+'/products/'},`<section class="pageHero"><div class="wrap"><h1>Diamond Tools</h1><div class="filters"><a class="chip" href="/products/">All Products</a>${d.cats.map(c=>`<a class="chip ${cat===c.slug?'active':''}" href="/products/?category=${esc(c.slug)}">${esc(c.name)}</a>`).join('')}</div></div></section><section><div class="wrap"><div class="grid">${items.map(x=>`<a class="card" href="/products/${esc(x.slug)}/">${mediaCard(x.image,x.name)}<div class="cardBody"><small>${esc(x.category||'')}</small><h3>${esc(x.name)}</h3><p>${esc(x.summary)}</p></div></a>`).join('')||'<div class="empty">No products.</div>'}</div></div></section>`,d)}
async function productPage(env,slugVal){const d=await siteData(env),p=await one(env.DB,"SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND p.status='published'",slugVal);if(!p)return new Response('Not Found',{status:404});const imgs=await rows(env.DB,"SELECT * FROM product_images WHERE product_id=? ORDER BY is_primary DESC,sort_order,id",p.id),specs=await rows(env.DB,"SELECT * FROM product_specs WHERE product_id=? ORDER BY sort_order,id",p.id);return shell({title:p.seo_title||`${p.name} | ${d.s.site_name||'SMUSU'}`,desc:p.seo_description||p.summary,canonical:`${env.SITE_URL}/products/${p.slug}/`},`<main class="wrap product"><p class="crumb">Home / Products / ${esc(p.category||'')}</p><div class="productGrid"><div class="gallery">${imgs.map(i=>mediaCard(i.object_key,i.alt_text||p.name)).join('')||mediaCard('',p.name)}</div><div><h1>${esc(p.name)}</h1><p class="lead">${esc(p.summary)}</p><p>${esc(p.description)}</p><a class="btn" href="/feedback/?product=${encodeURIComponent(p.name)}">Request Quote</a></div></div><section><h2>Specifications</h2><table>${specs.map(s=>`<tr><th>${esc(s.name)}</th><td>${esc(s.value)}</td></tr>`).join('')||'<tr><td>No specifications.</td></tr>'}</table></section></main>`,d)}
async function listPosts(env,u,type,title){const d=await siteData(env),filter=u.searchParams.get('type');let items;if(type==='news'&&filter)items=await rows(env.DB,"SELECT * FROM posts WHERE type=? AND status='published' ORDER BY id DESC",filter);else if(type==='news')items=await rows(env.DB,"SELECT * FROM posts WHERE type IN ('news','company_news','industry_news') AND status='published' ORDER BY id DESC");else items=await rows(env.DB,"SELECT * FROM posts WHERE type=? AND status='published' ORDER BY id DESC",type);return shell({title:`${title} | ${d.s.site_name||'SMUSU'}`,canonical:`${env.SITE_URL}/${title.toLowerCase()}/`},`<section class="pageHero"><div class="wrap"><h1>${title}</h1></div></section><section><div class="wrap"><div class="grid">${items.map(x=>`<a class="card" href="/${x.type==='case'?'cases':'news'}/${esc(x.slug)}/">${mediaCard(x.cover_key,x.title)}<div class="cardBody"><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p></div></a>`).join('')||'<div class="empty">No content.</div>'}</div></div></section>`,d)}
async function postPage(env,type,slugVal){const d=await siteData(env),types=type==='case'?['case']:['news','company_news','industry_news'];const qs=types.map(()=>'?').join(',');const p=await one(env.DB,`SELECT * FROM posts WHERE slug=? AND type IN (${qs}) AND status='published'`,slugVal,...types);if(!p)return new Response('Not Found',{status:404});return shell({title:p.seo_title||`${p.title} | ${d.s.site_name||'SMUSU'}`,desc:p.seo_description||p.summary,canonical:`${env.SITE_URL}/${type==='case'?'cases':'news'}/${p.slug}/`},`<section class="pageHero"><div class="wrap"><h1>${esc(p.title)}</h1><p>${esc(p.summary)}</p></div></section><article class="wrap article">${p.cover_key?`<img class="articleCover" src="/media/${esc(p.cover_key)}" alt="${esc(p.title)}">`:''}<div class="articleBody">${esc(p.content).replace(/\n/g,'<br>')}</div></article>`,d)}
async function videos(env){const d=await siteData(env),items=await rows(env.DB,"SELECT * FROM videos WHERE status='published' ORDER BY id DESC");return shell({title:`Videos | ${d.s.site_name||'SMUSU'}`,canonical:env.SITE_URL+'/videos/'},`<section class="pageHero"><div class="wrap"><h1>Videos</h1></div></section><section><div class="wrap"><div class="grid">${items.map(v=>`<article class="card"><div class="media">${v.video_key?`<video controls preload="metadata" ${v.poster_key?`poster="/media/${esc(v.poster_key)}"`:''}><source src="/media/${esc(v.video_key)}" type="video/mp4"></video>`:'VIDEO'}</div><div class="cardBody"><h3>${esc(v.title)}</h3><p>${esc(v.description)}</p></div></article>`).join('')||'<div class="empty">No videos.</div>'}</div></div></section>`,d)}
async function basic(env,key){const d=await siteData(env),p=await one(env.DB,"SELECT * FROM pages WHERE page_key=?",key);return shell({title:`${p?.title||key} | ${d.s.site_name||'SMUSU'}`,canonical:`${env.SITE_URL}/${key}/`},`<section class="pageHero"><div class="wrap"><h1>${esc(p?.title||key)}</h1><p>${esc(p?.subtitle||'')}</p></div></section><section><div class="wrap"><p>${esc(p?.content||'')}</p></div></section>`,d)}
async function feedback(env,u){const d=await siteData(env),product=u.searchParams.get('product')||'';return shell({title:`Feedback | ${d.s.site_name||'SMUSU'}`,canonical:env.SITE_URL+'/feedback/'},`<section class="pageHero"><div class="wrap"><h1>Feedback / Inquiry</h1></div></section><section><div class="wrap"><form class="feedback" method="post" action="/api/inquiry"><input name="name" required placeholder="Name"><input name="company" placeholder="Company"><input name="country" placeholder="Country"><input type="email" name="email" required placeholder="Email"><input name="phone" placeholder="WhatsApp / Phone"><input name="product" value="${esc(product)}" placeholder="Interested Product"><textarea name="message" required placeholder="Message"></textarea><input class="hp" name="website" tabindex="-1"><button class="btn" type="submit">Send Inquiry</button></form></div></section>`,d)}
async function submitInquiry(req,env){const f=await req.formData();if(f.get('website'))return new Response('OK');const name=String(f.get('name')||'').trim(),email=String(f.get('email')||'').trim(),message=String(f.get('message')||'').trim(),product=String(f.get('product')||'').trim();if(!name||!email||!message)return new Response('Missing fields',{status:400});await env.DB.prepare("INSERT INTO inquiries(name,email,company,country,phone,message,status) VALUES(?,?,?,?,?,?, 'new')").bind(name,email,String(f.get('company')||''),String(f.get('country')||''),String(f.get('phone')||''),product?`Product: ${product}\n${message}`:message).run();return Response.redirect(`${env.SITE_URL}/feedback/?sent=1`,303)}
async function media(req,env){const key=decodeURIComponent(new URL(req.url).pathname.slice(7)),o=await env.MEDIA.get(key);if(!o)return new Response('Not Found',{status:404});const h=new Headers();o.writeHttpMetadata(h);h.set('etag',o.httpEtag);h.set('cache-control','public,max-age=31536000,immutable');return new Response(req.method==='HEAD'?null:o.body,{headers:h})}
async function digestFile(file){const buf=await file.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',buf);return {buf,hex:[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}}
async function dedupUpload(file,env,prefix='media'){const {buf,hex}=await digestFile(file);const hit=await one(env.DB,"SELECT * FROM media_assets WHERE file_hash=?",hex);if(hit)return {...hit,reused:true};const ext=(file.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'').toLowerCase(),key=`${prefix}/${hex.slice(0,2)}/${hex}.${ext}`;await env.MEDIA.put(key,buf,{httpMetadata:{contentType:file.type}});const r=await env.DB.prepare("INSERT INTO media_assets(object_key,file_hash,file_name,mime_type,file_size) VALUES(?,?,?,?,?)").bind(key,hex,file.name,file.type,file.size).run();return {id:r.meta.last_row_id,object_key:key,file_hash:hex,file_name:file.name,mime_type:file.type,file_size:file.size,reused:false}}
async function api(req,env){const u=new URL(req.url);if(u.pathname==='/api/inquiry'&&req.method==='POST')return submitInquiry(req,env);if(u.hostname!==env.ADMIN_HOST)return J({error:'Forbidden'},403);
 if(u.pathname==='/api/admin/settings'&&req.method==='GET')return J(await settings(env));
 if(u.pathname==='/api/admin/settings'&&req.method==='PUT'){const b=await req.json(),keys=['site_name','company_name','phone','whatsapp','email','address','logo_key','favicon_key'];await env.DB.batch(keys.map(k=>env.DB.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(k,String(b[k]??''))));return J({success:true})}
 if(u.pathname==='/api/admin/media'&&req.method==='GET')return J(await rows(env.DB,"SELECT * FROM media_assets ORDER BY id DESC LIMIT 200"));
 if(u.pathname==='/api/admin/media'&&req.method==='POST'){const fd=await req.formData(),f=fd.get('file');if(!f||typeof f==='string')return J({error:'No file'},400);return J(await dedupUpload(f,env,'media'))}
 if(u.pathname==='/api/admin/categories'&&req.method==='GET')return J(await rows(env.DB,"SELECT * FROM categories ORDER BY sort_order,id"));
 if(u.pathname==='/api/admin/categories'&&req.method==='POST'){const b=await req.json(),r=await env.DB.prepare("INSERT INTO categories(name,slug,description,image_key,sort_order,status) VALUES(?,?,?,?,?,?)").bind(b.name,slug(b.slug||b.name),b.description||'',b.image_key||'',Number(b.sort_order||0),b.status||'published').run();return J({id:r.meta.last_row_id})}
 let m=u.pathname.match(/^\/api\/admin\/categories\/(\d+)$/);if(m&&req.method==='PUT'){const b=await req.json();await env.DB.prepare("UPDATE categories SET name=?,slug=?,description=?,image_key=?,sort_order=?,status=? WHERE id=?").bind(b.name,slug(b.slug||b.name),b.description||'',b.image_key||'',Number(b.sort_order||0),b.status||'published',+m[1]).run();return J({success:true})}
 m=u.pathname.match(/^\/api\/admin\/categories\/(\d+)\/image$/);if(m&&req.method==='POST'){const fd=await req.formData(),f=fd.get('file');if(!f||typeof f==='string')return J({error:'No image'},400);const asset=await dedupUpload(f,env,'categories');await env.DB.prepare("UPDATE categories SET image_key=? WHERE id=?").bind(asset.object_key,+m[1]).run();return J({success:true,object_key:asset.object_key,reused:asset.reused})}
 if(u.pathname==='/api/admin/products'&&req.method==='GET')return J(await rows(env.DB,"SELECT * FROM products ORDER BY id DESC"));
 if(u.pathname==='/api/admin/products'&&req.method==='POST'){const b=await req.json(),r=await env.DB.prepare("INSERT INTO products(name,slug,category_id,summary,description,status,seo_title,seo_description,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(b.name,slug(b.slug||b.name),b.category_id||null,b.summary||'',b.description||'',b.status||'draft',b.seo_title||'',b.seo_description||'',new Date().toISOString()).run();return J({id:r.meta.last_row_id})}
 m=u.pathname.match(/^\/api\/admin\/products\/(\d+)$/);if(m&&req.method==='PUT'){const b=await req.json();await env.DB.prepare("UPDATE products SET name=?,slug=?,category_id=?,summary=?,description=?,status=?,seo_title=?,seo_description=?,updated_at=? WHERE id=?").bind(b.name,slug(b.slug||b.name),b.category_id||null,b.summary||'',b.description||'',b.status||'draft',b.seo_title||'',b.seo_description||'',new Date().toISOString(),+m[1]).run();return J({success:true})}
 m=u.pathname.match(/^\/api\/admin\/products\/(\d+)\/images$/);if(m&&req.method==='GET')return J(await rows(env.DB,"SELECT * FROM product_images WHERE product_id=? ORDER BY is_primary DESC,sort_order,id",+m[1]));if(m&&req.method==='POST'){const fd=await req.formData(),f=fd.get('file'),pid=+m[1],p=await one(env.DB,"SELECT name FROM products WHERE id=?",pid);if(!p||!f||typeof f==='string')return J({error:'Invalid'},400);const asset=await dedupUpload(f,env,'images');const exists=await one(env.DB,"SELECT id FROM product_images WHERE product_id=? AND object_key=?",pid,asset.object_key);if(exists)return J({id:exists.id,object_key:asset.object_key,reused:true});const c=await one(env.DB,"SELECT COUNT(*) total FROM product_images WHERE product_id=?",pid),r=await env.DB.prepare("INSERT INTO product_images(product_id,object_key,alt_text,sort_order,is_primary) VALUES(?,?,?,?,?)").bind(pid,asset.object_key,p.name,+c.total+1,+c.total===0?1:0).run();return J({id:r.meta.last_row_id,object_key:asset.object_key,reused:asset.reused})}
 m=u.pathname.match(/^\/api\/admin\/products\/(\d+)\/images\/(\d+)\/primary$/);if(m&&req.method==='PUT'){await env.DB.batch([env.DB.prepare("UPDATE product_images SET is_primary=0 WHERE product_id=?").bind(+m[1]),env.DB.prepare("UPDATE product_images SET is_primary=1 WHERE id=? AND product_id=?").bind(+m[2],+m[1])]);return J({success:true})}
 m=u.pathname.match(/^\/api\/admin\/products\/(\d+)\/images\/(\d+)$/);if(m&&req.method==='DELETE'){await env.DB.prepare("DELETE FROM product_images WHERE id=? AND product_id=?").bind(+m[2],+m[1]).run();return J({success:true,note:'媒体文件保留在统一媒体库，避免误删其他引用'})}
 m=u.pathname.match(/^\/api\/admin\/products\/(\d+)\/specs$/);if(m&&req.method==='GET')return J(await rows(env.DB,"SELECT * FROM product_specs WHERE product_id=? ORDER BY sort_order,id",+m[1]));if(m&&req.method==='POST'){const b=await req.json(),c=await one(env.DB,"SELECT COUNT(*) total FROM product_specs WHERE product_id=?",+m[1]),r=await env.DB.prepare("INSERT INTO product_specs(product_id,name,value,sort_order) VALUES(?,?,?,?)").bind(+m[1],b.name,b.value,+c.total+1).run();return J({id:r.meta.last_row_id})}
 m=u.pathname.match(/^\/api\/admin\/products\/(\d+)\/specs\/(\d+)$/);if(m&&req.method==='DELETE'){await env.DB.prepare("DELETE FROM product_specs WHERE id=? AND product_id=?").bind(+m[2],+m[1]).run();return J({success:true})}
 if(u.pathname==='/api/admin/posts'&&req.method==='GET')return J(await rows(env.DB,"SELECT * FROM posts ORDER BY id DESC"));
 if(u.pathname==='/api/admin/posts'&&req.method==='POST'){const fd=await req.formData(),file=fd.get('cover'),title=String(fd.get('title')||'').trim();let cover=String(fd.get('cover_key')||'');if(file&&typeof file!=='string')cover=(await dedupUpload(file,env,'news')).object_key;const r=await env.DB.prepare("INSERT INTO posts(type,title,slug,summary,content,cover_key,status,seo_title,seo_description,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(String(fd.get('type')||'company_news'),title,slug(String(fd.get('slug')||title)),String(fd.get('summary')||''),String(fd.get('content')||''),cover,String(fd.get('status')||'draft'),String(fd.get('seo_title')||''),String(fd.get('seo_description')||''),new Date().toISOString()).run();return J({id:r.meta.last_row_id,cover_key:cover})}
 m=u.pathname.match(/^\/api\/admin\/posts\/(\d+)$/);if(m&&req.method==='POST'){const fd=await req.formData(),oldPost=await one(env.DB,"SELECT * FROM posts WHERE id=?",+m[1]);if(!oldPost)return J({error:'Post not found'},404);const file=fd.get('cover'),title=String(fd.get('title')||'').trim();let cover=oldPost.cover_key||'';if(file&&typeof file!=='string'&&file.size>0)cover=(await dedupUpload(file,env,'news')).object_key;await env.DB.prepare("UPDATE posts SET type=?,title=?,slug=?,summary=?,content=?,cover_key=?,status=?,seo_title=?,seo_description=?,updated_at=? WHERE id=?").bind(String(fd.get('type')||oldPost.type),title,slug(String(fd.get('slug')||title)),String(fd.get('summary')||''),String(fd.get('content')||''),cover,String(fd.get('status')||'draft'),String(fd.get('seo_title')||''),String(fd.get('seo_description')||''),new Date().toISOString(),+m[1]).run();return J({success:true,cover_key:cover})}
 if(u.pathname==='/api/admin/videos'&&req.method==='GET')return J(await rows(env.DB,"SELECT * FROM videos ORDER BY id DESC"));
 if(u.pathname==='/api/admin/videos'&&req.method==='POST'){const fd=await req.formData(),f=fd.get('file'),title=String(fd.get('title')||'Video');if(!f||typeof f==='string')return J({error:'No video'},400);const asset=await dedupUpload(f,env,'videos'),r=await env.DB.prepare("INSERT INTO videos(title,slug,description,video_key,status) VALUES(?,?,?,?,?)").bind(title,slug(title),String(fd.get('description')||''),asset.object_key,String(fd.get('status')||'draft')).run();return J({id:r.meta.last_row_id,key:asset.object_key,reused:asset.reused})}
 if(u.pathname==='/api/admin/inquiries'&&req.method==='GET'){const page=Math.max(1,Number(u.searchParams.get('page')||1)),status=u.searchParams.get('status')||'',limit=20,offset=(page-1)*limit;const count=status?await one(env.DB,"SELECT COUNT(*) total FROM inquiries WHERE status=?",status):await one(env.DB,"SELECT COUNT(*) total FROM inquiries");const items=status?await rows(env.DB,"SELECT * FROM inquiries WHERE status=? ORDER BY id DESC LIMIT ? OFFSET ?",status,limit,offset):await rows(env.DB,"SELECT * FROM inquiries ORDER BY id DESC LIMIT ? OFFSET ?",limit,offset);return J({items,page,pages:Math.max(1,Math.ceil(Number(count.total)/limit)),total:Number(count.total)})}
 m=u.pathname.match(/^\/api\/admin\/inquiries\/(\d+)\/status$/);if(m&&req.method==='PUT'){const b=await req.json();if(!['new','contacted','quoted','closed'].includes(b.status))return J({error:'Invalid status'},400);await env.DB.prepare("UPDATE inquiries SET status=? WHERE id=?").bind(b.status,+m[1]).run();return J({success:true})}
 return J({error:'Not Found'},404)}
async function app(req,env){const u=new URL(req.url);if(['/site.css','/admin.css','/admin.js','/robots.txt'].includes(u.pathname))return env.ASSETS.fetch(req);if(u.pathname.startsWith('/media/'))return media(req,env);if(u.pathname.startsWith('/api/'))return api(req,env);if(u.hostname===env.ADMIN_HOST){const a=new URL('/admin.html',req.url);return env.ASSETS.fetch(new Request(a.toString(),{headers:req.headers}))}if(u.pathname==='/')return home(env);if(/^\/products\/?$/.test(u.pathname))return productList(env,u);let m=u.pathname.match(/^\/products\/([^/]+)\/?$/);if(m)return productPage(env,decodeURIComponent(m[1]));if(/^\/about\/?$/.test(u.pathname))return basic(env,'about');if(/^\/contact\/?$/.test(u.pathname))return basic(env,'contact');if(/^\/feedback\/?$/.test(u.pathname))return feedback(env,u);if(/^\/news\/?$/.test(u.pathname))return listPosts(env,u,'news','News');if(/^\/cases\/?$/.test(u.pathname))return listPosts(env,u,'case','Cases');let pd=u.pathname.match(/^\/news\/([^/]+)\/?$/);if(pd)return postPage(env,'news',decodeURIComponent(pd[1]));pd=u.pathname.match(/^\/cases\/([^/]+)\/?$/);if(pd)return postPage(env,'case',decodeURIComponent(pd[1]));if(/^\/videos\/?$/.test(u.pathname))return videos(env);return new Response('Not Found',{status:404})}
export default{async fetch(req,env){try{return await app(req,env)}catch(e){console.error('SMUSU_V30',e?.stack||e);return new Response(`SMUSU V3.0 Error\n${e?.message||e}`,{status:500,headers:{"content-type":"text/plain; charset=utf-8"}})}}};
