const json=(v,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const esc=(v="")=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const slugify=(v="")=>String(v).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const one=(db,sql,...a)=>db.prepare(sql).bind(...a).first();
const rows=async(db,sql,...a)=>(await db.prepare(sql).bind(...a).all()).results||[];
const allowedVideoTypes=new Set(["video/mp4","video/webm","video/ogg","video/quicktime"]);
const allowedImageTypes=new Set(["image/jpeg","image/png","image/webp","image/gif"]);
const clamp=(v)=>Math.max(0,Math.min(100,Number.parseInt(v,10)||50));
async function digest(file){const b=await file.arrayBuffer();const h=await crypto.subtle.digest("SHA-256",b);return{b,hash:[...new Uint8Array(h)].map(v=>v.toString(16).padStart(2,"0")).join("")}}
async function upload(file,env,prefix){const {b,hash}=await digest(file);const hit=await one(env.DB,"SELECT * FROM media_assets WHERE file_hash=?",hash);if(hit)return{...hit,reused:true};const ext=(file.name.split(".").pop()||"bin").replace(/[^a-z0-9]/gi,"");const key=`${prefix}/${hash.slice(0,2)}/${hash}.${ext}`;await env.MEDIA.put(key,b,{httpMetadata:{contentType:file.type}});const r=await env.DB.prepare("INSERT INTO media_assets(object_key,file_hash,file_name,mime_type,file_size) VALUES(?,?,?,?,?)").bind(key,hash,file.name,file.type,file.size).run();return{id:r.meta.last_row_id,object_key:key,reused:false}}
function validFile(f){return f&&typeof f!=="string"&&f.size>0}
async function uniqueSlug(env,wanted,id=0){let s=slugify(wanted)||`video-${Date.now()}`;let n=2;while(await one(env.DB,"SELECT id FROM videos WHERE slug=? AND id<>?",s,id)){s=`${slugify(wanted)}-${n++}`}return s}
export async function videoAdminApi(req,env,u){let m;
 if(u.pathname==="/api/admin/videos"&&req.method==="GET")return json(await rows(env.DB,"SELECT * FROM videos ORDER BY sort_order,id DESC"));
 if(u.pathname==="/api/admin/videos"&&req.method==="POST"){const fd=await req.formData(),f=fd.get("file");if(!validFile(f))return json({error:"请选择视频文件"},400);if(!allowedVideoTypes.has(f.type))return json({error:"仅支持 MP4、WebM、OGG 或 MOV"},400);if(f.size>100*1024*1024)return json({error:"视频不能超过 100 MB"},400);const title=String(fd.get("title")||"Video").trim();if(!title)return json({error:"标题不能为空"},400);const a=await upload(f,env,"videos");let posterKey="";const poster=fd.get("poster");if(validFile(poster)){if(!allowedImageTypes.has(poster.type)||poster.size>5*1024*1024)return json({error:"封面须为 5 MB 以内的图片"},400);posterKey=(await upload(poster,env,"video-posters")).object_key}const slug=await uniqueSlug(env,String(fd.get("slug")||title));const now=new Date().toISOString();const r=await env.DB.prepare("INSERT INTO videos(title,slug,description,video_key,poster_key,mime_type,file_size,sort_order,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(title,slug,String(fd.get("description")||""),a.object_key,posterKey,f.type,f.size,+String(fd.get("sort_order")||0),String(fd.get("status")||"draft"),now,now).run();return json({id:r.meta.last_row_id,reused:a.reused})}
 m=u.pathname.match(/^\/api\/admin\/videos\/(\d+)$/);
 if(m&&req.method==="GET"){const v=await one(env.DB,"SELECT * FROM videos WHERE id=?",+m[1]);return v?json(v):json({error:"Video not found"},404)}
 if(m&&req.method==="POST"){const id=+m[1],old=await one(env.DB,"SELECT * FROM videos WHERE id=?",id);if(!old)return json({error:"Video not found"},404);const fd=await req.formData(),f=fd.get("file"),poster=fd.get("poster");let key=old.video_key,mime=old.mime_type||"",size=old.file_size||0,posterKey=old.poster_key||"",reused=false;if(validFile(f)){if(!allowedVideoTypes.has(f.type))return json({error:"仅支持 MP4、WebM、OGG 或 MOV"},400);if(f.size>100*1024*1024)return json({error:"视频不能超过 100 MB"},400);const a=await upload(f,env,"videos");key=a.object_key;mime=f.type;size=f.size;reused=a.reused}if(validFile(poster)){if(!allowedImageTypes.has(poster.type)||poster.size>5*1024*1024)return json({error:"封面须为 5 MB 以内的图片"},400);posterKey=(await upload(poster,env,"video-posters")).object_key}if(String(fd.get("remove_poster")||"")==="1")posterKey="";const title=String(fd.get("title")||old.title).trim();const slug=await uniqueSlug(env,String(fd.get("slug")||title),id);await env.DB.prepare("UPDATE videos SET title=?,slug=?,description=?,video_key=?,poster_key=?,mime_type=?,file_size=?,sort_order=?,status=?,updated_at=? WHERE id=?").bind(title,slug,String(fd.get("description")||""),key,posterKey,mime,size,+String(fd.get("sort_order")||0),String(fd.get("status")||"draft"),new Date().toISOString(),id).run();return json({success:true,video:await one(env.DB,"SELECT * FROM videos WHERE id=?",id),reused})}
 if(m&&req.method==="DELETE"){const r=await env.DB.prepare("DELETE FROM videos WHERE id=?").bind(+m[1]).run();return r.meta.changes?json({success:true}):json({error:"Video not found"},404)}
 return null;
}
export async function videoPublicHtml(env){const a=await rows(env.DB,"SELECT * FROM videos WHERE status='published' ORDER BY sort_order,id DESC");return `<section class="pageHero"><div class="wrap"><h1>Videos</h1></div></section><section><div class="wrap grid">${a.map(v=>`<article class="card"><div class="media"><video controls preload="metadata" ${v.poster_key?`poster="/media/${esc(v.poster_key)}"`:""}><source src="/media/${esc(v.video_key)}" type="${esc(v.mime_type||"video/mp4")}"></video></div><div class="cardBody"><h3>${esc(v.title)}</h3><p>${esc(v.description||"")}</p></div></article>`).join("")||'<div class="empty">No published videos.</div>'}</div></section>`}
export function position(v){return `${clamp(v.image_position_x)}% ${clamp(v.image_position_y)}%`}
